insert into public.interests (category, name, emoji) values
  -- Sport
  ('sport', 'Running', '🏃'),
  ('sport', 'Football', '⚽'),
  ('sport', 'Basketball', '🏀'),
  ('sport', 'Tennis', '🎾'),
  ('sport', 'Padel', '🥎'),
  ('sport', 'Musculation', '🏋️'),
  ('sport', 'Yoga', '🧘'),
  ('sport', 'Natation', '🏊'),
  ('sport', 'Cyclisme', '🚴'),
  ('sport', 'Boxe', '🥊'),
  ('sport', 'Danse', '💃'),
  ('sport', 'Escalade', '🧗'),
  ('sport', 'Crossfit', '🤸'),
  ('sport', 'Golf', '⛳'),
  ('sport', 'Ski / Snowboard', '🎿'),
  ('sport', 'Volley-ball', '🏐'),
  ('sport', 'Surf', '🏄'),
  ('sport', 'Arts martiaux', '🥋'),
  -- Plein air
  ('plein_air', 'Randonnée', '🥾'),
  ('plein_air', 'Camping', '⛺'),
  ('plein_air', 'Pêche', '🎣'),
  ('plein_air', 'Voile', '⛵'),
  ('plein_air', 'Jardinage', '🌱'),
  ('plein_air', 'Voyage', '✈️'),
  ('plein_air', 'Pique-nique', '🧺'),
  ('plein_air', 'VTT', '🚵'),
  -- Culture
  ('culture', 'Cinéma', '🎬'),
  ('culture', 'Lecture', '📚'),
  ('culture', 'Musées', '🖼️'),
  ('culture', 'Concerts', '🎤'),
  ('culture', 'Théâtre', '🎭'),
  ('culture', 'Jeux vidéo', '🎮'),
  ('culture', 'Jeux de société', '🎲'),
  ('culture', 'Langues étrangères', '🗣️'),
  -- Créatif
  ('creatif', 'Photographie', '📷'),
  ('creatif', 'Musique / Instrument', '🎸'),
  ('creatif', 'Peinture / Dessin', '🎨'),
  ('creatif', 'Cuisine', '🍳'),
  ('creatif', 'Écriture', '✍️'),
  ('creatif', 'DIY / Bricolage', '🔨'),
  -- Social
  ('social', 'Bénévolat', '🤝'),
  ('social', 'Bars / Sorties', '🍸'),
  ('social', 'Brunch', '🥐'),
  ('social', 'Œnologie', '🍷'),
  ('social', 'Animaux', '🐾'),
  -- Bien-être
  ('bien_etre', 'Méditation', '🧘‍♀️'),
  ('bien_etre', 'Spiritualité', '🕉️'),
  ('bien_etre', 'Nutrition', '🥗'),
  ('bien_etre', 'Développement personnel', '🌿')
on conflict (name) do nothing;
